baseURL = '/'
languageCode = 'en-us'
title = 'Sequoia Fabrica Makerspace'
buildFuture = true
buildDrafts = false
pagination.pagerSize = 12
DefaultContentLanguage = 'en'
defaultContentLanguage = 'en'
pluralizelisttitles = 'false'
refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = '/'
relativeURLs = true
canonifyURLs = true
timeout = 60000
rssLimit = 3
enableInlineShortcodes = true

summaryLength=0

[markup]

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'onesenterprise'
tabWidth = 4

[permalinks]
posts = '/:year/:month/:slugorfilename/'
categories = '/:slug/'

[params]
author = 'Camille Teicheira'
newsletter = 'https://dashboard.mailerlite.com/forms/1197290/139047052633965606/share'
description = 'A volunteer-run, membership-based, community workshop in San Francisco.'
donate = 'https://opencollective.com/sequoia-fabrica'
events = 'https://bookwhen.com/sequoiafabrica#focus=ev-s5jb-20250313160000'
wiki = 'https://wiki.sequoiafabrica.org/wiki/Main_Page'
email = 'info@sequoiafabrica.org'
mastadon = 'https://sfba.social/@sequoiafabrica'
instagram = 'https://www.instagram.com/sequoia.fabrica'
tiktok = 'https://www.tiktok.com/@sequoiafabrica'

[params.headless_cms]
engine = "sveltia"
site_url = "https://your-site.org"
locale = 'en-us'
media_folder = 'static/uploads'
public_folder = '/uploads'

[params.headless_cms.backend]
name = "github"
repo = "camilleanne/sequoia_fabrica_blog"

[[params.headless_cms.collections]]
name = "blog"
label = "Blog Posts"
label_singular = "Blog Post"
folder = "content/posts"
slug = "{{slug}}/index"
create = true
# this does not work the way decap or svetlia says:
# decap: https://decapcms.org/docs/collection-folder/#media-and-public-folder
# svetlia: https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#using-a-custom-media-folder-for-a-collection
# TODO: find the bug. kill the bug.
media_folder = "./{{slug}}/images/"
public_folder = "./{{slug}}/images/"

[[params.headless_cms.collections.fields]]
label = "Title"
name = "title"
widget = "string"

[[params.headless_cms.collections.fields]]
label = "Publish Date"
name = "date"
widget = "datetime"

[[params.headless_cms.collections.fields]]
label = "Summary"
name = "summary"
widget = "string"

[[params.headless_cms.collections.fields]]
label = "In Draft?"
name = "draft"
widget = "boolean"
default = true

[[params.headless_cms.collections.fields]]
label = "Authors"
name = "authors"
widget = "list"

[[params.headless_cms.collections.fields]]
label = "Tags"
name = "tags"
widget = "list"
required = false
# TODO: this doesn't work
options = ["one", "two", "three", "four", "five"]

[[params.headless_cms.collections.fields]]
label = "Categories"
name = "categories"
widget = "list"
default = ["general"]
add_to_top = true

[[params.headless_cms.collections.fields]]
label = "Featured image"
name = "featured_image"
widget = "image"
required = false

[[params.headless_cms.collections.fields]]
label = "Body"
name = "body"
widget = "markdown"

[params.headless_cms.collections.sortable_fields]
fields = ["title", "published_date", "author"]

[params.headless_cms.collections.sortable_fields.default]
field = "published_date"
direction = "descending"

[menu]

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about'
weight = 1

[[menu.main]]
identifier = 'events'
name = 'Events'
url = 'https://bookwhen.com/sequoiafabrica'
weight = 2

[[menu.main]]
identifier = 'donate'
name = 'Donate'
url = 'https://opencollective.com/sequoia-fabrica'
weight = 3

[[menu.main]]
identifier = 'membership'
name = 'Membership'
url = '/membership'
weight = 4

[[menu.main]]
identifier = 'faq'
name = 'FAQ'
url = '/faq'
weight = 5

[[menu.main]]
identifier = 'partner'
name = 'Partner'
url = '/partner'
weight = 6

[[menu.main]]
identifier = 'contact'
name = 'Contact'
url = '/contact'
weight = 7

[[menu.main]]
identifier = 'blog'
name = 'Blog'
url = '/posts'
weight = 8

[taxonomies]
author = 'authors'
tag = 'tags'
category = 'categories'

[related]
includeNewer = true
threshold = 80
toLower = false

[[related.indices]]
name = 'tags'
weight = 100

[module]

[[module.imports]]
path = "github.com/privatemaker/headless-cms"

[outputs]
home = ["HTML", "RSS", "HeadlessCMSConfig"]
